
name <- c("Alfie", "Belinda", "Charlie", "Delilah")
writeClipboard(name)
write.table(name,"name")
write.table(name,"name.txt",row.names = FALSE,col.names = NA)
write.table(name,"name.txt",row.names = FALSE,col.names = 'name')
write.table(name,"name.txt",row.names = FALSE,col.names = 'name',quote = FALSE)
write.table(name,"name.txt",sep = '\t')
age = c(34,28,31,38)
smoker = c(TRUE,FALSE,FALSE,TRUE)
A = data.frame(name,age,smoker)
write.table(A,"data frame.txt",quote = FALSE,sep = '\t',col.names = NA)
write.csv(name,"name.csv")
write.csv(name,"name.csv",row.names = FALSE)
write.csv(A,"data frame.csv",quote = FALSE)
#write.xlsx(name,"name.xlsx")
